development:
  adapter: mysql2
  database: zyt
  host: localhost
  username: root
  password: "123456"
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: zyt
  host: 192.168.0.226
  username: root
  password: "123456"
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: zyt
  host: 192.168.0.226
  username: root
  password: "123456"
  pool: 5
  timeout: 5000

